source "https://rubygems.org"

# GitHub Pages gem includes Jekyll and common plugins
gem "github-pages", group: :jekyll_plugins

# Windows compatibility
gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]
gem "webrick", "~> 1.7"

# Additional plugins
group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end
